# Generated by Django 6.0.6 on 2026-07-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_chunk_embedding_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
