# Generated by Django 6.0.7 on 2026-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_document_observability"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="end_offset",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chunk",
            name="start_offset",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
